// <auto-generated />
namespace Northwind_EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Northwind_10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Northwind_10));
        
        string IMigrationMetadata.Id
        {
            get { return "201811121138248_Northwind_1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
